SET(MYSQL_DEFINITIONS ${PC_MYSQL_CFLAGS_OTHER})

FIND_PATH(
    MYSQL_INCLUDE_DIR
    NAMES "mysql.h"
    PATH_SUFFIXES "mysql"
)

FIND_LIBRARY(MYSQL_LIBS NAMES mysqlclient
   HINTS
   ${PC_MYSQL_LIBDIR}
   ${PC_MYSQL_LIBRARY_DIRS}
)

SET(ENABLE_XORM ON)
SET(ENABLE_MYSQL ON)

if(ENABLE_XORM)
  add_definitions(-D_ENABLE_XORM_)
  if(ENABLE_MYSQL)
     add_definitions(-DXORM_ENABLE_MYSQL)
  endif()
  if(ENABLE_SQLITE)
    add_definitions(-DXORM_ENABLE_SQLITE)
  if(ENABLE_SQLITE_CODEC)
   add_definitions(-DSQLITE_HAS_CODEC)
  endif()
  endif()
endif()


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(mysql DEFAULT_MSG MYSQL_LIBS MYSQL_INCLUDE_DIR)
