IF (NOT EV_LIBRARIES)
  MESSAGE("-- Setting default Event Library Directory")
  SET(EV_LIBRARIES "/usr/local/lib/libevent.a")
ENDIF (NOT EV_LIBRARIES)

MESSAGE("-- EV_LIBRARIES\t" ${EV_LIBRARIES})

IF (NOT EV_INCLUDE_DIRS)
  MESSAGE("-- Setting default EV Include Directory")
  SET(EV_INCLUDE_DIRS "/usr/local/include/")
ENDIF (NOT EV_INCLUDE_DIRS)

MESSAGE("-- EV_INCLUDE_DIRS\t" ${EV_INCLUDE_DIRS})

INCLUDE_DIRECTORIES(${EV_INCLUDE_DIRS})
LINK_DIRECTORIES(${EV_INCLUDE_DIRS})

SET(
  REQUIRED_LIBRARIES
  ${REQUIRED_LIBRARIES}
  ${EV_LIBRARIES}
)
